import React from 'react'

function LazyLoaded() {
  return (
    <div>
      <h2 className='text-2xl mb-4 font-bold underline underline-offset-1'>React Router : Lazy Loading</h2>
      <div>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam luctus lacus ut leo tempor, ac viverra felis varius. Vivamus elementum efficitur quam a ultricies. Aliquam vel rhoncus velit. Phasellus tempus neque nec aliquam auctor. Vestibulum eleifend pulvinar sapien et feugiat. Aenean auctor et mauris vel suscipit. Nam efficitur turpis diam, pellentesque hendrerit ante varius ut. In ullamcorper porttitor rhoncus. Maecenas vel scelerisque urna.
      Curabitur pretium auctor consequat. Maecenas eu augue convallis, blandit diam eu, aliquet lorem. Nulla eget lectus eget dui dictum pretium nec vel elit. Nulla sed consectetur tortor. Sed orci est, varius eget auctor at, varius eget augue. Duis at leo eu justo venenatis auctor. Nunc aliquet ante sed molestie convallis. Phasellus eu enim sed nisl imperdiet facilisis. Vestibulum euismod enim nec semper commodo. Suspendisse quam lorem, blandit ut risus et, vestibulum bibendum diam. Cras eu urna euismod, elementum mi ut, vehicula mi. Maecenas convallis mauris et dui suscipit commodo.
      Sed pharetra pulvinar tristique. Proin quis sem facilisis neque suscipit condimentum. Nullam ex massa, iaculis at diam ut, volutpat aliquam lacus. Donec at fringilla augue. Sed eget libero quis felis sagittis dictum. Ut pellentesque eget ligula dictum bibendum. Pellentesque imperdiet efficitur eleifend. Praesent luctus bibendum risus, id finibus lacus cursus quis. Mauris aliquet sollicitudin vulputate. Sed vel neque turpis. Sed rhoncus lacinia justo non tristique. Donec et porttitor ipsum, id ornare neque. Curabitur blandit euismod enim. Integer vel vulputate nisl, non condimentum lorem.
      Vestibulum consequat ullamcorper euismod. Fusce porttitor orci in libero tristique pellentesque. Donec eu facilisis neque. Pellentesque euismod orci et dui efficitur, vitae interdum odio tincidunt. Vivamus velit arcu, rhoncus ac nibh at, laoreet euismod diam. Aenean rhoncus est sed pellentesque facilisis. Nunc consequat, nisi ac placerat eleifend, turpis sapien vulputate leo, vel dictum orci libero non purus. Praesent tincidunt eleifend sapien, a egestas ante ultrices sit amet. Sed sed dolor venenatis, dapibus purus ut, tempus neque. Sed consequat at turpis vitae sagittis. Pellentesque ex massa, iaculis in felis ut, molestie suscipit purus. Cras et enim porttitor, congue ante et, elementum erat. Sed sed gravida dui. Aliquam tempus commodo orci quis imperdiet.
      Curabitur et venenatis massa. Aenean cursus nisl maximus sapien hendrerit, ac aliquam nisi dignissim. Nam eros sem, imperdiet eu laoreet vitae, molestie id lectus. Morbi ullamcorper maximus mollis. Donec vitae nisi scelerisque, aliquet sapien vitae, tincidunt orci. Aliquam fringilla aliquam lectus sed iaculis. Fusce eget venenatis dui, ac finibus elit. Duis sem sapien, ullamcorper vel augue a, scelerisque hendrerit erat.
      Sed eu dignissim dui, in fermentum dui. Proin dignissim tempor enim, et pharetra dui viverra ac. Mauris iaculis magna tortor, vel porttitor ante condimentum ac. Vestibulum vel ligula ut dui porttitor feugiat volutpat a tortor. Donec congue porta eros, porttitor condimentum tortor. Donec eget semper mi. Maecenas metus nulla, gravida quis hendrerit et, molestie quis nunc. Ut efficitur hendrerit urna, suscipit lobortis libero sollicitudin vel.
      Vestibulum consectetur vel justo at eleifend. In tincidunt vestibulum ex ut consectetur. In turpis nibh, pharetra ac augue in, finibus lacinia lectus. Vestibulum luctus magna quis magna viverra interdum. Donec sapien lacus, gravida nec dui ac, dictum varius justo. Maecenas non congue elit. Vestibulum ac arcu a urna posuere suscipit. Etiam massa libero, pellentesque ac bibendum sed, consectetur at leo.
      Curabitur malesuada augue at egestas pretium. In elementum fermentum eros, sit amet dictum enim placerat quis. Donec eget scelerisque turpis, a vestibulum eros. Cras consequat hendrerit ligula, sed pellentesque purus fringilla vel. Sed sodales imperdiet ante in eleifend. Aenean porttitor justo augue, in euismod est posuere ac. Nunc diam felis, vehicula at facilisis a, congue quis tellus.
      Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla et faucibus turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam iaculis metus nisl, eu consequat justo pellentesque a. Nulla mollis magna non arcu volutpat dignissim nec id justo. Nunc nec odio tincidunt nibh vulputate gravida. Suspendisse sit amet orci ac elit condimentum convallis nec quis nisi. Donec congue convallis lacus, sit amet bibendum nunc fermentum quis. Fusce aliquam porttitor leo sed porttitor. Integer et neque lacus. Sed efficitur in metus et pharetra. Suspendisse a pretium nisi, a ullamcorper elit. Sed ultricies nisl eget tristique eleifend. In sagittis erat mauris, a finibus lectus faucibus et. Praesent ut dapibus sem. Suspendisse facilisis arcu tortor, at dictum lectus accumsan a.
      Nulla et neque vel orci faucibus ultricies quis eu lacus. Vestibulum condimentum nisl varius ullamcorper molestie. Maecenas metus mauris, tempor in venenatis et, posuere id ligula. Quisque mauris mauris, gravida cursus ligula sit amet, cursus pretium lorem. Nam in felis fringilla metus mattis ultrices in et eros. Nunc a condimentum massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nisl dui, tincidunt sed sagittis id, aliquet at diam. Suspendisse maximus mauris ac nunc egestas, luctus dapibus quam varius. Cras in pharetra urna, eu egestas est. Curabitur ut magna ut metus fringilla condimentum id in ante. Nam tincidunt dolor vel felis dapibus ornare. Nunc urna nibh, elementum sit amet scelerisque vitae, imperdiet vel sapien. Nam ut nibh porta, lobortis sapien nec, accumsan quam. Mauris tincidunt nec dui non hendrerit.
      Cras feugiat sodales posuere. Nulla pretium egestas sem, vitae elementum nunc suscipit a. Nullam nibh leo, sagittis quis magna eget, sodales fermentum nulla. Suspendisse potenti. Etiam vel lectus non nibh pellentesque lacinia et a massa. Phasellus sagittis ex quam, ac elementum nisl fringilla id. Nam a auctor ante.
      Aenean nec mollis turpis. Quisque pulvinar, nisi eu bibendum scelerisque, libero tortor fermentum nibh, non tempus risus nunc at arcu. Duis ut lacus in metus tristique fermentum sed ut elit. Praesent ipsum justo, ullamcorper id blandit vel, ornare et ligula. Mauris maximus orci eget lectus porta, sit amet maximus sapien mattis. Vivamus vel mollis turpis. Mauris condimentum quam metus, ac lacinia odio faucibus a. Nulla tincidunt sagittis mi et maximus. Phasellus et velit in est efficitur pharetra. Fusce et purus ultricies, ultricies augue id, ultricies lectus.
      Aliquam dolor ligula, blandit eu bibendum vel, commodo ac sem. Ut dictum efficitur libero, a egestas dui dapibus ut. Morbi fringilla quam in sollicitudin scelerisque. Etiam eleifend fermentum lectus, sit amet tempor ante semper ut. Aenean viverra tellus non neque ornare pretium vitae vel orci. Duis vel ligula risus. Nullam faucibus tellus massa, id congue enim imperdiet id. Praesent cursus interdum turpis, id placerat massa ornare a. Nulla cursus iaculis feugiat. Mauris a molestie dui, quis lacinia nulla. Vestibulum risus ante, malesuada nec pharetra blandit, rutrum a leo. Aliquam erat volutpat.
      Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nam pharetra nisl neque, a finibus sapien volutpat nec. Quisque ultricies justo nec nisi aliquam, in ornare dui consectetur. Curabitur id feugiat justo. Mauris mollis sagittis mattis. Etiam et suscipit dolor. Suspendisse non nibh sit amet mauris tempus tempus. Nunc et semper ex. Ut maximus faucibus risus, vitae fermentum nulla lobortis nec. Morbi et lacinia augue. Curabitur mattis sit amet nulla ac ullamcorper. Sed commodo ut sem vitae porta.
      Nunc arcu dolor, ultrices eget mollis a, accumsan non lacus. Etiam vel dui eros. Proin ut posuere lacus, quis porta neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas tempor justo a posuere convallis. In hac habitasse platea dictumst. Quisque consectetur elit dui, quis convallis massa viverra sed. Mauris at ultricies leo, sed volutpat lacus. Proin eleifend quam quis neque suscipit, in porttitor nulla elementum. Mauris eu ipsum tincidunt, maximus leo quis, euismod elit. Nulla ornare felis sem, at rutrum nunc fringilla non. Etiam sed leo vehicula, varius mauris et, mollis lacus.
      Ut finibus non arcu in rutrum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris scelerisque ante ut iaculis facilisis. Praesent suscipit faucibus justo, non aliquet ante suscipit ut. Maecenas eu elit viverra risus mattis tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam rhoncus justo nec elit vestibulum, ac pharetra orci tristique. Fusce sit amet placerat quam. Pellentesque a malesuada risus. Pellentesque massa justo, viverra nec sem ac, aliquam vulputate ex. Phasellus sed mauris vehicula, fermentum eros in, aliquet nulla. Praesent lobortis velit nisi, ac porta augue sagittis eu. Etiam at interdum dui, a gravida tellus. Nulla gravida pellentesque molestie. Aliquam blandit volutpat mattis.
      Sed malesuada consequat ligula, non fringilla turpis scelerisque nec. Donec interdum aliquam imperdiet. Nullam a tellus non purus iaculis bibendum non non nisl. Cras et libero feugiat, pretium urna sit amet, dictum libero. Etiam luctus, tellus quis tincidunt auctor, urna arcu maximus lacus, quis blandit quam lorem ut ex. Curabitur dignissim nibh a fermentum pharetra. Quisque viverra erat luctus dui tempor, quis tempus eros consectetur. Nulla blandit nibh vel est fringilla egestas.
      Praesent in cursus mi. Proin est nisi, vehicula eget elit a, tempus pharetra urna. Sed vitae quam in ligula auctor efficitur vitae ac elit. Nunc sem est, accumsan vel consectetur nec, ullamcorper malesuada velit. Ut in quam vehicula, elementum est quis, sagittis augue. Curabitur in eleifend mauris, vel feugiat neque. Vestibulum nec vestibulum leo, vehicula faucibus est. Curabitur ipsum orci, porta vel rutrum eget, fringilla vel nisi. Praesent fringilla urna ac magna mollis porta. Nulla tristique sapien quis est varius, non molestie velit molestie. Quisque pellentesque, mi vel posuere consequat, ligula nisl viverra magna, fermentum mattis nisl turpis eu elit. Curabitur interdum erat nec fermentum tincidunt. Sed tortor dolor, molestie vitae lectus quis, rhoncus ultrices lorem. Mauris mi nunc, dignissim nec ex id, pulvinar iaculis erat. Etiam pellentesque cursus lorem nec volutpat.
      Fusce convallis accumsan nibh et fermentum. Sed lacus nunc, condimentum eu metus sit amet, consequat feugiat quam. Vestibulum rhoncus pharetra ultricies. Nunc quam sapien, faucibus porta aliquam sit amet, ullamcorper et erat. Mauris ut enim vel libero sodales fermentum. Nunc porta ligula ac lectus aliquam tempus. Curabitur non facilisis nisl. Duis non elit eros. Fusce laoreet, urna in accumsan auctor, dolor dui pharetra felis, vel luctus justo sem quis massa. Fusce vestibulum diam vel tortor bibendum, consectetur tincidunt odio pellentesque. Nam eu lacus elit. Cras maximus nulla eget bibendum auctor. Donec consectetur fringilla ligula quis rutrum. Vivamus a urna vel lectus euismod dictum nec in augue. Fusce porta, est ac elementum dictum, elit lorem rhoncus purus, eu facilisis erat ligula in turpis. Vestibulum vitae magna ut diam maximus euismod eget vel nulla.
      Mauris suscipit velit eu sem egestas porttitor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vestibulum risus vitae sodales aliquet. Nullam varius urna aliquam, tempus metus in, mattis augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque ac tristique ex. Curabitur sed metus sit amet leo porta bibendum. Aliquam vel leo tincidunt, iaculis purus eu, vestibulum sapien. Suspendisse elementum consectetur metus, eget aliquet eros consectetur in. Sed convallis in elit scelerisque fringilla.
      </div>
    </div>
  )
}

export default LazyLoaded